package GUI;

import SC_Kom.Message;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class MainScreen {
    private JPanel mainPanel;
    private JTextArea chat;
    private JTextField chatInput;
    private JButton sendButton;
    private JPanel chatPanel;
    private JPanel gamePanel;
    private JComboBox atPlayer;
    private JTextArea playerOnline;
    private JScrollPane scrollText;
    private JPanel mainMenuPanel;
    private JPanel connect4Panel;
    private JPanel chompPanel;
    private ArrayList<String> players = new ArrayList<String>();
    private String playerName;

    public MainScreen(JFrame frame, String playerName) {
        this.playerName = playerName;
        frame.setContentPane(mainPanel);
        frame.setTitle("GAME");
        frame.pack();
        frame.setVisible(true);
        frame.setExtendedState(Frame.MAXIMIZED_BOTH);
        atPlayer.addItem("@ALL");
        sendButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String message = chatInput.getText();
                chatInput.setText("");
                processChatMessage(message);
            }
        });

    }

    private void processChatMessage(String message) {
        String name = (String) atPlayer.getSelectedItem();
        addChatMessage("You: " + message);
        synchronized (this) {
            if (name.equals("@ALL")) {
                Message.sendMessage(7);
                Message.sendMessage(message);
            } else {
                Message.sendMessage(6);
                Message.sendMessage(name);
                Message.sendMessage(message);
            }
        }
    }

    public void addChatMessage(String message) {
        chat.setText(chat.getText() + "\n" + message);
    }

    public void addPlayer(String player) {
        players.add(player);
        if (!playerName.equals(player)) {
            atPlayer.addItem(player);
        }
        updatePlayerOnline();
    }

    public void removePlayer(String player) {
        int ptr = players.indexOf(player);
        players.remove(ptr);
        atPlayer.removeItem(player);
        updatePlayerOnline();
    }

    private void updatePlayerOnline() {
        String text = "";
        for (String player : players) {
            text += player + "\n";
        }
        playerOnline.setText(text);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        chatPanel = new JPanel();
        chatPanel.setLayout(new GridBagLayout());
        mainPanel.add(chatPanel, BorderLayout.EAST);
        chatInput = new JTextField();
        chatInput.setColumns(15);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        chatPanel.add(chatInput, gbc);
        sendButton = new JButton();
        sendButton.setText("Send");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        chatPanel.add(sendButton, gbc);
        atPlayer = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        chatPanel.add(atPlayer, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        chatPanel.add(spacer1, gbc);
        scrollText = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        chatPanel.add(scrollText, gbc);
        chat = new JTextArea();
        chat.setEditable(false);
        chat.setRows(20);
        scrollText.setViewportView(chat);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        chatPanel.add(scrollPane1, gbc);
        playerOnline = new JTextArea();
        playerOnline.setRows(8);
        scrollPane1.setViewportView(playerOnline);
        gamePanel = new JPanel();
        gamePanel.setLayout(new CardLayout(0, 0));
        mainPanel.add(gamePanel, BorderLayout.CENTER);
        mainMenuPanel = new JPanel();
        mainMenuPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gamePanel.add(mainMenuPanel, "Card1");
        final JLabel label1 = new JLabel();
        label1.setText("MAINMENU");
        mainMenuPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        mainMenuPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        connect4Panel = new JPanel();
        connect4Panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        gamePanel.add(connect4Panel, "Card2");
        chompPanel = new JPanel();
        chompPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        gamePanel.add(chompPanel, "Card3");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
